In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [5]:
[1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]

In [6]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [7]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [10]:
a[2] = 10
a

array([ 1,  2, 10,  4])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
np.linspace(1, 2, 10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [19]:
zeros_matrix = np.zeros((5, 2))
zeros_matrix

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
ones_matrix = np.ones((5, 2))
ones_matrix

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
constant_matrix = np.full((5, 2), 3)
constant_matrix

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

In [23]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [24]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
n.shape

(3, 3)

In [26]:
n.ndim

2

In [27]:
n[0, 1] =20

In [28]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [30]:
np.random.rand(5, 10)

array([[0.2812449 , 0.69831543, 0.57608995, 0.38470653, 0.40514497,
        0.96279426, 0.14649297, 0.2852842 , 0.61347094, 0.84792408],
       [0.74430177, 0.18298627, 0.53998354, 0.6844734 , 0.36138292,
        0.05203404, 0.40593306, 0.43413434, 0.99236101, 0.21830546],
       [0.505293  , 0.85329656, 0.97988108, 0.06526956, 0.9733102 ,
        0.54952041, 0.63185578, 0.79019884, 0.18753049, 0.33772706],
       [0.49826276, 0.41251169, 0.83915384, 0.1888    , 0.52848699,
        0.3529862 , 0.30509014, 0.50161772, 0.82142161, 0.53784702],
       [0.16524817, 0.50305455, 0.29845521, 0.62814495, 0.03599079,
        0.63792082, 0.11907665, 0.85878022, 0.54509903, 0.23470046]])