In [2]:
import numpy as np

In [3]:
u = np.array([2, 7, 5, 6])
v = np.array([3, 4, 8, 6])

# addition 
u + v

# subtraction 
u - v

# scalar multiplication 
2 * v

array([ 6,  8, 16, 12])

In [4]:
u + v

array([ 5, 11, 13, 12])

In [5]:
u - v

array([-1,  3, -3,  0])

In [6]:
u*v

array([ 6, 28, 40, 36])

In [7]:
u/v

array([0.66666667, 1.75      , 0.625     , 1.        ])

In [12]:
u.shape

(4,)

In [14]:
u.shape[0]

4

In [13]:
v.shape

(4,)

In [15]:
v.shape[0]

4

In [8]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [10]:
vector_vector_multiplication(u, v)

np.float64(110.0)

In [11]:
np.dot(u, v)

np.int64(110)

In [23]:
U = np.array([
    [1, 2, 3, 7],
    [4, 5, 6, 8]
])
U

array([[1, 2, 3, 7],
       [4, 5, 6, 8]])

In [24]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [25]:
matrix_vector_multiplication(U, v)

array([ 77., 128.])